 -- =========================================
-- CUSTOMER PURCHASE ANALYSIS PROJECT
-- =========================================

CREATE DATABASE customer_behaviour;
USE customer_behaviour;

SELECT * FROM customer;

-- ============================================================
-- 🔹 DATA EXPLORATION
-- ============================================================

-- Q1. How many total customers are present in the dataset?
SELECT COUNT(*) AS total_customers
FROM customer;

-- Q2. What are the different product categories available?
SELECT DISTINCT category
FROM customer;

-- Q3. What are the minimum and maximum purchase amounts?
SELECT MIN(purchase_amount) AS min_purchase,
       MAX(purchase_amount) AS max_purchase
FROM customer;

-- ============================================================
-- 🔹 DESCRIPTIVE ANALYSIS
-- ============================================================

-- Q4. How are customers distributed based on gender?
SELECT gender,
       COUNT(*) AS total_customers
FROM customer
GROUP BY gender;

-- Q5. What is the overall average purchase amount?
SELECT ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer;

-- Q6. How many customers have used discounts?
SELECT discount_applied,
       COUNT(*) AS total_customers
FROM customer
GROUP BY discount_applied;

-- ============================================================
-- 🔹 BUSINESS INSIGHTS
-- ============================================================

-- Q7. What is the total revenue generated by male vs female customers?
SELECT gender,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- Q8. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,
       purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM customer
      );

-- Q9. Do subscribed customers spend more compared to non-subscribers?
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q10. How does shipping type affect the average purchase amount?
SELECT shipping_type,
       ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- ============================================================
-- 🔹 ADVANCED ANALYTICS
-- ============================================================

-- Q11. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(review_rating),2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q12. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
           100.0 * SUM(CASE 
                         WHEN discount_applied = 'Yes' THEN 1 
                         ELSE 0 
                       END) / COUNT(*), 2
       ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q13. How can customers be segmented into New, Returning, and Loyal groups?
WITH customer_type AS (
    SELECT customer_id,
           CASE 
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segment;

-- Q14. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category 
               ORDER BY COUNT(customer_id) DESC
           ) AS rank_num
    FROM customer
    GROUP BY category, item_purchased
)
SELECT category,
       item_purchased,
       total_orders
FROM item_counts
WHERE rank_num <= 3;

-- Q15. Are repeat buyers (more than 5 previous purchases) more likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q16. What is the revenue contribution of each age group?
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- =========================================
-- FINAL COMMIT
-- =========================================
COMMIT;
 
 